{Derechos Reservados Kevin Hernandez/10-5/COTEPECOS/2011}
program Proyecto_1_16;
uses crt,dos;
begin
        clrscr;
        textcolor(green);
        writeln('*****************************************************************************');
        writeln('Programa Nø: 16 ');
        writeln('Descripci¢n: Muestra los 15 colores que utiliza el textcolor del 0 al 14');
        writeln('Elaborado por: Kevin Hernandez Rostran');
        writeln('Fecha: 28/6/2011');
        writeln('*****************************************************************************');
        writeln('');
        writeln('');
        gotoxy(14,9);
	textbackground(7);
        textcolor(0);
        writeln('          textcolor(0)   NEGRO               ');
        gotoxy(14,10);
        textcolor(1);
        writeln('          textcolor(1)   AZUL OBSCURO        ');
        gotoxy(14,11);
        textcolor(2);
        writeln('          textcolor(2)   VERDE               ');
        gotoxy(14,12);
        textcolor(3);
        writeln('          textcolor(3)   VERDE AGUA          ');
        gotoxy(14,13);
        textcolor(4);
        writeln('          textcolor(4)   ROJO                ');
        gotoxy(14,14);
        textcolor(5);
        writeln('          textcolor(5)   MORADO              ');
        gotoxy(14,15);
        textcolor(6);
        writeln('          textcolor(6)   DORADO              ');
        gotoxy(14,16);
        textbackground(5);
        textcolor(7);
        writeln('          textcolor(7)   BLANCO              ');
        gotoxy(14,17);
        textcolor(8);
        writeln('          textcolor(8)   GRIS                ');
        gotoxy(14,18);
        textcolor(9);
        writeln('          textcolor(9)   AZUL                ');
        gotoxy(14,19);
        textcolor(10);
        writeln('          textcolor(10)  VERDE CLARO         ');
        gotoxy(14,20);
        textcolor(11);
        writeln('          textcolor(11)  CELESTE             ');
        gotoxy(14,21);
        textcolor(12);
        writeln('          textcolor(12)  ROJO                ');
        gotoxy(14,22);
        textcolor(13);
        writeln('          textcolor(13)  FUCSIA              ');
        gotoxy(14,23);
        textcolor(14);
        writeln('          textcolor(14)  AMARILLO            ');
        readln;
end.

